---
development:
  cloud_name: devsinc122
  api_key: '549795145737926'
  api_secret: 336EfYG2w7bm-adVp70r76zFYRE
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: devsinc122
  api_key: '549795145737926'
  api_secret: 336EfYG2w7bm-adVp70r76zFYRE
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: devsinc122
  api_key: '549795145737926'
  api_secret: 336EfYG2w7bm-adVp70r76zFYRE
  enhance_image_tag: true
  static_file_support: false
